version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Server
    container_name: comparacion_grpc_server
    ports:
      - 50051:50051
  comentarista:
    build:
      context: .
      dockerfile: Comentarista
    container_name: comparacion_grpc_comentarista
    network_mode: host
    depends_on: 
      - server
  oyente:
    build:
      context: .
      dockerfile: Oyente
    container_name: comparacion_grpc_oyente
    network_mode: host
    depends_on: 
      - comentarista