version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Server
    container_name: comparacion_rest_server
    ports:
      - 4567:4567
  commentator:
    build:
      context: .
      dockerfile: Commentator
    container_name: comparacion_rest_comentarista
    network_mode: host
    depends_on:
      - server
  listener:
    build:
      context: .
      dockerfile: Listener
    container_name: comparacion_rest_oyente
    network_mode: host
    depends_on:
      - commentator