version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Server
    container_name: base_server
    ports:
      - 50051:50051
  client:
    build:
      context: .
      dockerfile: Client
    container_name: base_client
    network_mode: host
    depends_on: 
      - server